[package]
name = "async_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }

[workspace]
resolver = "2"
members = ["async_demo_sleep"]

